version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh